Don't check cache on each access
Jikoo/EnchantableBlocks pull request #14
Opened 2020-11-03 18:06 UTC by sgdc3

Improves performance on large servers

2020-11-03 18:38 UTC, Jikoo requested changes
Overall not a fan - would prefer 1a7971b and 7dbf7e1 to be separate from this PR as they're separate concerns.

2020-11-03 18:38 UTC, Jikoo commented on src/main/java/com/github/jikoo/enchantableblocks/EnchantableBlocksPlugin.java
> +import org.bukkit.Bukkit;
Unused import.

2020-11-03 18:38 UTC, Jikoo commented on src/main/java/com/github/jikoo/enchantableblocks/util/Cache.java
> +		//this.lazyCheck();
If you're going to comment out a line of code, it should just be deleted - that's what version control is for. Several cases of this.

2020-11-03 18:39 UTC, Jikoo commented
Not sure why you'd want to move to a scheduler-based approach when there could just be a cooldown applied (i.e. in lazy check if now < next check time do nothing). Since the scheduler isn't running async we're still doing the same work on the main thread, just less frequently and with larger batch sizes. This should actually result in larger lag spikes.

I am now noticing that I hilariously managed to put 6000 in for the duration of a minute in several places instead of 60000.

2020-11-05 02:23 UTC, sgdc3 commented
The main concern of the previous approach is the huge allocation rate it causes, causing frequent GC pauses.
The task will never run with a much larger batch of data, in 5 seconds the server wont't unload many chunks.
I'll split the pr asap.

2020-11-05 03:51 UTC, Jikoo commented
That's valid, forgot how aggressive new chunk unloading got. Looking at the queue I'm also not sure why I used a TreeMap instead of using a Queue and stopping when a peeked value isn't up for expiration beyond maybe my own laziness.

2020-11-05 13:39 UTC, Jikoo commented
Okay, I've pushed a fix for my stupidity, actually pushed the gitignore I had locally and had never included (whoops), cherry picked in your removal of Guava, and added a cooldown of 10 seconds (which can be added to the config if it seems necessary) between lazy checks. Let me know if that resolves this.

I'm still going to be looking into improving the cache, but I think I might just need to rewrite the entire expiration system.

2020-11-06 15:38 UTC, sgdc3 commented
Looks good, thank you!

2020-11-06 15:38 UTC, closed without merging